project_name: cortex-proxy
env:
  - COSIGN_EXPERIMENTAL=true
  - GO111MODULE=on
before:
  hooks:
    - go mod download
gomod:
  proxy: false
builds:
  - main: ./cmd/loki-proxy
    binary: "loki-proxy-{{ .Os }}-{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
  - main: ./cmd/cortex-proxy/
    binary: "cortex-proxy-{{ .Os }}-{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/peak-scale/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    > [!TIP]
    > [Read this documentation](https://github.com/peak-scale/{{ .ProjectName }}/blob/{{ .Tag }}/SECURITY.md) to see how you can verify an artifacts we are releasing.

    > [!IMPORTANT]
    > **Kubernetes compatibility**
    > Note that the Capsule project offers support only for the latest minor version of Kubernetes.
    > Backwards compatibility with older versions of Kubernetes and OpenShift is [offered by vendors](https://projectcapsule.dev/support/).

    ## Cortex Proxy

    [![Artifact Hub](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/cortex-proxy)](https://artifacthub.io/packages/search?repo=cortex-proxy)

    **Docker Images**
    - `ghcr.io/peak-scale/{{ .ProjectName }}/cortex-proxy:{{ .Version }}`
    - `ghcr.io/peak-scale/{{ .ProjectName }}/cortex-proxy:latest`

    ## Loki Proxy

    [![Artifact Hub](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/loki-proxy)](https://artifacthub.io/packages/search?repo=loki-proxy)

    **Docker Images**
    - `ghcr.io/peak-scale/{{ .ProjectName }}/loki-proxy:{{ .Version }}`
    - `ghcr.io/peak-scale/{{ .ProjectName }}/loki-proxy:latest`


    Thanks to all the contributors! 🚀 🦄
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - '^rebase:'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
  groups:
    # https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional
    - title: '🛠 Dependency updates'
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: '✨ New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: '🐛 Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: '📖 Documentation updates'
      regexp: ^.*?docs(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: '🛡️ Security updates'
      regexp: ^.*?(sec)(\([[:word:]]+\))??!?:.+$
      order: 500
    - title: '🚀 Build process updates'
      regexp: ^.*?(build|ci)(\([[:word:]]+\))??!?:.+$
      order: 600
    - title: '📦 Other work'
      order: 9999
sboms:
  - artifacts: archive
signs:
- cmd: cosign
  args:
  - "sign-blob"
  - "--output-signature=${signature}"
  - "${artifact}"
  - "--yes"
  artifacts: all
