---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 15m
  timeout: 10m
  targetNamespace: monitoring-system
  releaseName: "loki"
  chart:
    spec:
      chart: loki
      version: "6.36.1"
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 24h
  install:
    createNamespace: false
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    minio:
      enabled: false
    global:
      clusterDomain: "cluster.local"
      dnsService: "kube-dns"
      dnsNamespace: "kube-system"
      extraArgs:
        - -config.expand-env=true
      extraEnvFrom:
        - secretRef:
            name: lgtm-s3-credentials
    backend:
      extraEnvFrom:
      - secretRef:
          name: lgtm-s3-credentials
    monitoring:
      serviceMonitor:
        enabled: true
      dashboards:
        enabled: true
        annotations:
          k8s-sidecar-target-directory: "/tmp/dashboards/Monitoring Stack"
    loki:
      auth_enabled: true
      querier:
        multi_tenant_queries_enabled: true
      # https://grafana.com/docs/loki/latest/operations/storage/retention/
      compactor:
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        delete_request_store: s3
      limits_config:
        per_stream_rate_limit: 1024M
        per_stream_rate_limit_burst: 2048M
        cardinality_limit: 20000
        ingestion_burst_size_mb: 1000
        ingestion_rate_mb: 2000
        # Delete from storage logs data older than 180 Days
        retention_period: 24h
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
        query_timeout: 300s
        volume_enabled: true
      schemaConfig:
        configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h
      storage:
        shared_store: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        type: s3
        s3:
          endpoint: minio.monitoring-system.svc.cluster.local:9000
          region: us-east-1
          accessKeyId: "${S3_ACCESS_KEY}"
          secretAccessKey: "${S3_ACCESS_SECRET}"
          s3ForcePathStyle: true
          insecure: true
